export const dataFeed = [
  {
    id: 1,
    name: 'Yuri',
    month: 'april',
    day: 'saturday',
    nation: 'brasil',
    user: 'yurygargarin',
    year: ' 2021 - 07h às 10h',
    location: 'Praia de Miami - Natal/RN - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/19.jpg') },
      { id: '2', image: require('../../assets/images/surf/2.jpg') },
      { id: '3', image: require('../../assets/images/surf/3.jpg') },
      { id: '4', image: require('../../assets/images/surf/4.jpg') },
      { id: '5', image: require('../../assets/images/surf/5.jpg') },
    ],
  },
  {
    id: 2,
    day: 'monday',
    name: 'Fernando',
    nation: 'brasil',
    month: 'january',
    user: 'fernandosilva',
    year: ' 2021 - 07h às 10h',
    location: 'Maracaipe - Porto de Galinhas/PE - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/4.jpg') },
      { id: '2', image: require('../../assets/images/surf/5.jpg') },
      { id: '3', image: require('../../assets/images/surf/6.jpg') },
      { id: '4', image: require('../../assets/images/surf/4.jpg') },
    ],
  },
  {
    id: 3,
    name: 'Fabio',
    day: 'tuesday',
    nation: 'brasil',
    month: 'november',
    user: 'fabiocouto',
    year: ' 2021 - 07h às 10h',
    location: 'São Miguel do Gostoso - Touros/RN - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/7.jpg') },
      { id: '2', image: require('../../assets/images/surf/8.jpg') },
      { id: '3', image: require('../../assets/images/surf/9.jpg') },
    ],
  },
  {
    id: 4,
    day: 'friday',
    month: 'july',
    name: 'Marley',
    user: 'marley',
    nation: 'brasil',
    year: ' 2021 - 07h às 10h',
    location: 'Barra da Lagoa - Florianópolis/SC - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/10.jpg') },
      { id: '2', image: require('../../assets/images/surf/11.jpg') },
    ],
  },
  {
    id: 5,
    name: 'Bob',
    user: 'bobjow',
    day: 'wednesday',
    nation: 'brasil',
    month: 'december',
    year: ' 2021 - 07h às 10h',
    location: 'Sobre as ondas - Astúrias Guarujá - Guarujá/SP - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/13.jpg') },
      { id: '2', image: require('../../assets/images/surf/14.jpg') },
      { id: '3', image: require('../../assets/images/surf/15.jpg') },
      { id: '4', image: require('../../assets/images/surf/4.jpg') },
      { id: '5', image: require('../../assets/images/surf/5.jpg') },
      { id: '6', image: require('../../assets/images/surf/8.jpg') },
    ],
  },
  {
    id: 6,
    name: 'Yago',
    day: 'saturday',
    nation: 'brasil',
    month: 'february',
    user: 'yagocabral',
    year: ' 2021 - 07h às 10h',
    location: 'Tombo - Guarujá/SP - ',
    feedImages: [
      { id: '1', image: require('../../assets/images/surf/16.jpg') },
      { id: '2', image: require('../../assets/images/surf/17.jpg') },
      { id: '3', image: require('../../assets/images/surf/18.jpg') },
      { id: '4', image: require('../../assets/images/surf/15.jpg') },
    ],
  },
];

export const dataStories = [
  {
    id: 1,
    name: 'add',
    image: require('../../assets/images/cam.png'),
  },
  {
    id: 2,
    name: 'Alex',
    image: require('../../assets/images/surf/10.jpg'),
  },
  {
    id: 3,
    name: 'Lucas',
    image: require('../../assets/images/surf/11.jpg'),
  },
  {
    id: 4,
    name: 'Pedro',
    image: require('../../assets/images/surf/12.jpg'),
  },
  {
    id: 5,
    name: 'Enzo',
    image: require('../../assets/images/surf/13.jpg'),
  },
  {
    id: 6,
    name: 'Julia',
    image: require('../../assets/images/surf/14.jpg'),
  },
  {
    id: 7,
    name: 'Marcos',
    image: require('../../assets/images/surf/15.jpg'),
  },
  {
    id: 8,
    name: 'Josue',
    image: require('../../assets/images/surf/16.jpg'),
  },
  {
    id: 9,
    name: 'Natanael',
    image: require('../../assets/images/surf/17.jpg'),
  },
  {
    id: 10,
    name: 'Marley',
    image: require('../../assets/images/surf/18.jpg'),
  }
];

export const imagesGalery = [
  { id: '1', image: require('../../assets/images/surf/1.jpg') },
  { id: '2', image: require('../../assets/images/surf/2.jpg') },
  { id: '3', image: require('../../assets/images/surf/3.jpg') },
  { id: '4', image: require('../../assets/images/surf/4.jpg') },
  { id: '5', image: require('../../assets/images/surf/5.jpg') },
  { id: '6', image: require('../../assets/images/surf/6.jpg') },
  { id: '7', image: require('../../assets/images/surf/7.jpg') },
  { id: '8', image: require('../../assets/images/surf/8.jpg') },
  { id: '9', image: require('../../assets/images/surf/9.jpg') },
  { id: '10', image: require('../../assets/images/surf/10.jpg') },
  { id: '11', image: require('../../assets/images/surf/11.jpg') },
  { id: '12', image: require('../../assets/images/surf/12.jpg') },
  { id: '13', image: require('../../assets/images/surf/13.jpg') },
  { id: '14', image: require('../../assets/images/surf/14.jpg') },
  { id: '15', image: require('../../assets/images/surf/15.jpg') },
  { id: '16', image: require('../../assets/images/surf/16.jpg') },
  { id: '17', image: require('../../assets/images/surf/17.jpg') },
  { id: '18', image: require('../../assets/images/surf/18.jpg') },
];